export const mockProducts = [
  {
    id: 1,
    name: 'Cappuccino',
    description: 'A classic blend of espresso, steamed milk, and foam.',
    ingredients: ['Espresso', 'Steamed milk', 'Foamed milk'],
    sizes: ['Small', 'Medium', 'Large'],
    image: 'cappuccino.png',
    prices: [3.45, 4.45, 4.95],
    tags: ['Vegetarian', 'Fresh', 'All'],
  },
  {
    id: 2,
    name: 'Americano',
    description: 'Espresso diluted with hot water.',
    ingredients: ['Espresso', 'Hot water'],
    sizes: ['Small', 'Medium', 'Large'],
    image: 'americano.png',
    prices: [3.45, 4.45, 4.95],
    tags: ['Vegan', 'Sugar-Free', 'Lactose-Free', 'All'],
  },
  {
    id: 3,
    name: 'Espresso',
    description:
      'A rich and strong coffee shot, perfect for a quick energy boost.',
    ingredients: ['Espresso'],
    sizes: ['Single Shot', 'Double Shot'],
    image: 'espresso.png',
    prices: [2.5, 4.45],
    tags: ['Vegetarian', 'Bold', 'All'],
  },
  {
    id: 4,
    name: 'Iced Macchiato',
    description: 'Espresso with milk, caramel, and ice.',
    ingredients: ['Espresso', 'Milk', 'Caramel syrup', 'Ice'],
    sizes: ['Small', 'Medium', 'Large'],
    image: 'icedcaramellmacchiato.png',
    prices: [4.45, 5.45, 6.95],
    tags: ['Vegetarian', 'Fresh', 'All'],
  },
  {
    id: 5,
    name: 'Affogato',
    description: 'Espresso poured over vanilla ice cream.',
    ingredients: ['Espresso', 'Vanilla ice cream'],
    sizes: ['Small'],
    image: 'affogato.png',
    prices: [4.95],
    tags: ['Vegetarian', 'All'],
  },
  {
    id: 6,
    name: 'Flat White',
    description: 'A velvety smooth espresso with steamed milk.',
    ingredients: ['Espresso', 'Steamed milk'],
    sizes: ['Small', 'Medium', 'Large'],
    image: 'flatwhite.png',
    prices: [3.45, 4.45, 4.95],
    tags: ['Vegetarian', 'Fresh', 'All'],
  },
];
